# -*- coding: utf-8 -*-
"""TGbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P8x1wpBbsSCP2mADc1IBuh1SzojNh9zh
"""

import asyncio
from telegram import Update
from telegram.ext import ApplicationBuilder, CommandHandler, MessageHandler, filters, ContextTypes

# Sample Q&A dictionary
qa_dict = {
    "what is ordinary least squares": "OLS estimates regression coefficients by minimizing the sum of squared residuals.",
    "what is multicollinearity": "Multicollinearity is when independent variables in a regression are highly correlated.",
    "what is heteroscedasticity": "Heteroscedasticity means the variance of the residuals is not constant.",
    "explain hypothesis testing": "Hypothesis testing evaluates assumptions about population parameters using test statistics.",
    "what is r-squared": "R-squared measures the proportion of variance in the dependent variable explained by the model."
}

# Define command handler
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(
        "Welcome to the Econometrics Q&A Bot! Ask a question like 'What is ordinary least squares?'"
    )

# Define message handler
async def handle_question(update: Update, context: C ontextTypes.DEFAULT_TYPE):
    question = update.message.text.lower()
    answer = qa_dict.get(question, "Sorry, I don't have an answer to that question yet.")
    await update.message.reply_text(answer)

# Async function to run the bot
async def main():
    app = ApplicationBuilder().token("7606587987:AAHT2VrZSq7v5HvoydLhrqwWkfOirIqbORo").build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_question))

    await app.initialize()
    await app.start()
    print("Bot is running...")
    await app.updater.start_polling()
    # Keep it alive
    await asyncio.Event().wait()

# Run the bot using asyncio
await main()
